version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

workflows:
  deploy:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: aws
          persist-workspace: true
          path: ./.infrastructure/modules/lambda/
          requires:
            - terraform/validate
      - approve_for_deploy:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: aws
          path: ./.infrastructure/modules/lambda/
          filters:
            branches:
              only: main
          requires:
            - approve_for_deploy
      - approve_terraform_destroy:
          type: approval
          requires:
            - terraform/apply
      - terraform/destroy:
          attach-workspace: true
          context: aws
          path: ./.infrastructure/modules/lambda/
          filters:
            branches:
              only: main
          requires:
            - approve_terraform_destroy