version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

workflows:
  deploy:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          working_directory: ~/project/.infrastructure/modules/lambda/
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate