version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

workflows:
  deploy:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: aws
          persist-workspace: true
          path: ./.infrastructure/modules/lambda/
          requires:
            - terraform/validate